//@authors Nathaniel Wendt, Raga Srinivasan
//@date 11/26/2013

package datastructures;

import java.sql.Timestamp;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;

//A close poll message is generated by the owner of a poll and is sent to
//The admin to be forwarded to all relevant client parties
public class ClosePoll extends Message implements Serializable {
	protected String uuid;
	protected TimeSlot finalSlot;
	protected ArrayList<String> recipients;
	
	public ClosePoll(String uuid, TimeSlot finalSlot){
		super("");
		this.mType = MessageType.CLOSEPOLL;
		this.uuid = uuid;
		this.finalSlot = finalSlot;
	}
	
	public void setRecipients(ArrayList<String> recipients){
		this.recipients = recipients;
	}
	
	public ArrayList<String> getRecipients(){
		return this.recipients;
	}
	
	//@Gets the unique ID of the poll
	public String getUUID(){
		return this.uuid;
	}
	
	//@returns the final time slot chosen by the host of the poll
	//@returns the timeslot value chosen
	public TimeSlot getFinalSlot(){
		return this.finalSlot;
	}

}