//@authors Nathaniel Wendt, Raga Srinivasan
//@date 11/26/2013

package datastructures;

import java.util.*;
import java.io.Serializable;

//A new poll object holds a newly created poll and a list of recipients
//This message is generated by a client and sent to the admin to deal with accordingly
public class NewPoll extends Message implements Serializable {
	protected Poll poll;
	protected ArrayList<String> recipients;
	
	public NewPoll(String sender, Poll poll, ArrayList<String> recipients){
		super(sender);
		this.mType = MessageType.NEWPOLL;
		this.setPoll(poll);
		this.setRecipients(recipients);
	}
	
	//@Gets the sender of the new poll
	//@returns the string value of the senders name
	public String getSender(){
		return this.sender;
	}

	//@Gets the poll
	//@returns the poll within the message
	public Poll getPoll() {
		return poll;
	}

	//@Sets the poll
	//@param poll - poll to set value to be
	public void setPoll(Poll poll) {
		this.poll = poll;
	}

	//@Gets the list of recipients for the new poll
	//@returns an arraylist of strings of usernames
	public ArrayList<String> getRecipients() {
		return recipients;
	}

	//@Sets the list of recipients for the new poll
	//@param recipients - list of usernames to set as poll recipients
	public void setRecipients(ArrayList<String> recipients) {
		this.recipients = recipients;
	}
}